// Regenerate with: bun mods/thoughts/scripts/build-fixtures.ts
// The test kit runs with no fs, so fixtures ship as a generated module.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const here = join(import.meta.dir, '../tests/fixtures')
const read = (path: string) => readFileSync(join(here, path), 'utf8')
const replies = Object.fromEntries(
  readdirSync(join(here, 'replies'))
    .filter(name => name.endsWith('.md'))
    .sort()
    .map(name => [name.replace(/\.md$/, ''), read(join('replies', name))]),
)
const plans = { midrun: read('plan-midrun.md'), tick: read('tick-plan.md') }
writeFileSync(
  join(here, 'fixtures.gen.ts'),
  `// Generated by scripts/build-fixtures.ts — do not edit.\nexport const REPLIES: Record<string, string> = ${JSON.stringify(replies, null, 2)}\n\nexport const PLANS = ${JSON.stringify(plans, null, 2)}\n`,
)
